baseurl: ''
languageCode: en-us
title: Linguist | اللُّــغَــوِيّــــ
googleAnalytics: ""
//preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩
disableHugoGeneratorInject: true
pluralizeListTitles: false
minify: true


taxonomies:
  category: categories
  tag: tags
  author: authors
  
  
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
#    - identifier: projects
#      name: Projects
#      url: /projects/
#      weight: 5

params:
  description: "Hop Hopsdfsdfsdfsdfsdf."
  FooterText: "© LinguistPage | 2022"
  

frontmatter:
  author: Tarek Shehata
  github: 'https://github.com/linguistfm'
  sitename: ######
  twitter: '######'

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: atom


markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: emacs
    tabWidth: 4
