baseurl: ''
languageCode: en-us
title: Linguist | اللُّــغَــوِيّــــ
googleAnalytics: "G-RLYXZR4QEW"
preserveTaxonomyNames: false
footnotereturnlinkcontents: ↩
disableHugoGeneratorInject: true
pluralizeListTitles: false
minify: true

staticDir:
- static

taxonomies:
  category: categories
  tag: tags
  arword: arwords
#  arexp: arexps
  enword: enwords
#  enexp: enexps
  arlexicon: arlexicons
  enlexicon: enlexicons
  author: authors
#  translator: translators
#  citation: citations
  source: sources
  pubhouse: pubhouses
  pubyear: pubyears
  language: languages
  
 



trans:
- categories : الأقسام

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
#    - identifier: books
#      name: books
#      url: /hmm/
#      weight: 1

params:
  description: "موسوعة اللسانيات الحاسوبية التعليمية"
  FooterText: "  اللُّــغَــوِيّــــ | 2023 ©"
  

frontmatter:
  author: Tarek Shehata
  github: 'https://github.com/linguistfm'
  sitename: ######
  twitter: '######'

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: atom


markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: emacs
    tabWidth: 4
